In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

import mlflow 
import mlflow.sklearn

In [3]:
RANDOM_STATE = 42
EXPERIMENT_NAME = "logistic_regression_training"

In [4]:
# MLFLOW Setup
mlflow.set_experiment(EXPERIMENT_NAME)

2025/12/30 21:39:30 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/12/30 21:39:30 INFO mlflow.store.db.utils: Updating database tables
2025/12/30 21:39:30 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/30 21:39:30 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade  -> 451aebb31d03, add metric step
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
2025/12/30 21:39:30 INFO alembic.runtime.migration: Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade bda7b8c39065 -> cbc13b556ace, add V3 trace schema columns
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade cbc13b556ace -> 770bee3ae1dd, add assessments table
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 770bee3ae1dd -> a1b2c3d4e5f6, add spans table
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade a1b2c3d4e5f6 -> de4033877273, create entity_associations table
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade de4033877273 -> 1a0cddfcaa16, Add webhooks and webhook_events tables
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 1a0cddfcaa16 -> 534353b11cbc, add scorer tables
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 534353b11cbc -> 71994744cf8e, add evaluation datasets
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 71994744cf8e -> 3da73c924c2f, add outputs to dataset record
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade 3da73c924c2f -> bf29a5ff90ea, add jobs table
2025/12/30 21:39:31 INFO alembic.runtime.migration: Running upgrade bf29a5ff90ea -> 1bd49d398cd23, add secrets tables
2025/12/30 21:39:31 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/30 21:39:31 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/30 21:39:31 INFO mlflow.tracking.fluent: Experiment with name 'logistic_regression_training' does not exist. Creating a new experiment.

<Experiment: artifact_location=('file:c:/Users/Aman/OneDrive/Documents/GitHub/ML-Models/ML-EXPERIMENT '
 '1/notebooks/mlruns/1'), creation_time=1767110971810, experiment_id='1', last_update_time=1767110971810, lifecycle_stage='active', name='logistic_regression_training', tags={}>

In [14]:
dataPath = "../data/titanic.csv"
df = pd.read_csv(dataPath)
df.head()
df.shape

(891, 12)

In [19]:
TARGET_COL = "Survived"

NUMERIC_FEATURES = [
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

CATEGORICAL_FEATURES = [
    "Sex",
    "Embarked",
    "Pclass"
]

x = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
y = df[TARGET_COL]

x

      Age  SibSp  Parch     Fare     Sex Embarked  Pclass
0    22.0      1      0   7.2500    male        S       3
1    38.0      1      0  71.2833  female        C       1
2    26.0      0      0   7.9250  female        S       3
3    35.0      1      0  53.1000  female        S       1
4    35.0      0      0   8.0500    male        S       3
..    ...    ...    ...      ...     ...      ...     ...
886  27.0      0      0  13.0000    male        S       2
887  19.0      0      0  30.0000  female        S       1
888   NaN      1      2  23.4500  female        S       3
889  26.0      0      0  30.0000    male        C       1
890  32.0      0      0   7.7500    male        Q       3

[891 rows x 7 columns]

In [20]:
xTrain, xTest, yTrain, yTest = train_test_split(
    x,
    y,
    random_state= RANDOM_STATE,
    test_size = 0.2,
    stratify=y
)

print(xTrain.shape, xTest.shape)

(712, 7) (179, 7)

In [36]:
# Save split for reuse
xTrain.to_csv("../data/X_train.csv", index=False)
xTest.to_csv("../data/X_test.csv", index=False)
yTrain.to_csv("../data/y_train.csv", index=False)
yTest.to_csv("../data/y_test.csv", index=False)

In [24]:
# Preprocessing 
print(df[NUMERIC_FEATURES].isna().sum())
print(df[CATEGORICAL_FEATURES].isna().sum())

Age      177
SibSp      0
Parch      0
Fare       0
dtype: int64
Sex         0
Embarked    2
Pclass      0
dtype: int64

### Why Median Imputation for Age?
- Age is right-skewed
- Contains outliers (infants, elderly)
- Median is robust to outliers

### Why Most Frequent for Embarked?
- Only 2 missing values
- Highly imbalanced categorical feature
- Adding a "missing" category would add noise

In [30]:
numericTransformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categoricalTransformer = Pipeline(steps = [
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numericTransformer, NUMERIC_FEATURES),
        ("cat", categoricalTransformer, CATEGORICAL_FEATURES)
    ]
)

df[CATEGORICAL_FEATURES]

        Sex Embarked  Pclass
0      male        S       3
1    female        C       1
2    female        S       3
3    female        S       1
4      male        S       3
..      ...      ...     ...
886    male        S       2
887  female        S       1
888  female        S       3
889    male        C       1
890    male        Q       3

[891 rows x 3 columns]

In [31]:
# MODEL 
model = LogisticRegression(
    solver = "liblinear",
    C = 1.0,
    max_iter=100,
    random_state=RANDOM_STATE
)

In [33]:
pipeline = Pipeline(steps = [
    ("preprocessing", preprocessor),
    ("model", model)
])

In [34]:
# Training and MlFlow Logging
with mlflow.start_run():
    mlflow.log_param("model_type", "logistic_regression")
    mlflow.log_param("solver", model.solver)
    mlflow.log_param("C", model.C)
    mlflow.log_param("max_iter", model.max_iter)

    pipeline.fit(xTrain, yTrain)
    yPrediction = pipeline.predict(xTest)

    accuracy = accuracy_score(yTest, yPrediction)
    precision = precision_score(yTest, yPrediction)
    recall = recall_score(yTest, yPrediction)

    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)

    # Model Artifact
    mlflow.sklearn.log_model(
        sk_model=pipeline,
        artifact_path="model"
    )

2025/12/30 22:51:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

In [35]:
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")

Accuracy  : 0.8045
Precision : 0.7931
Recall    : 0.6667